GET http://localhost:4040/
###
POST http://localhost:4049/
Content-Type: application/json

{
    "_": {
        "number": 1
    },
    "plusOne": {
        "number": 1
    },
    "plusTwo": {
        "number": 3
    },
    "plusThree": {
        "number": 5
    }
}
###