GET http://localhost:4040/
###
http://localhost:4049/

{
    "_": {
        "number": 1
    },
    "plusOne": {
        "number": 40
    },
    "plusTwo": {
        "number": 3
    },
    "plusThree": {
        "number": 5
    }
}
###